#pragma once
#include <string>

enum class TokenType {
    RUNE, SPELL, CHANNEL, WHEN, ORWHEN, OTHERWISE,
    WHILE, FORGE, IN, SUMMON, FROM, BLESSED, CURSED,
    AND, OR, NOT, RITUAL, UNLEASH,
    IDENTIFIER, NUMBER, STRING, INTERP_STRING,
    PLUS, MINUS, STAR, SLASH,
    EQUAL, EQUAL_EQUAL, NOT_EQUAL, GREATER, GREATER_EQUAL, LESS, LESS_EQUAL,
    LPAREN, RPAREN, COLON, COMMA,
    INDENT, DEDENT, NEWLINE, END_OF_FILE,
    LBRACKET, RBRACKET
};

struct Token {
    TokenType type;
    std::string lexeme;
    int line;
};